# Kitty — Tokyo Night

# Fuente
font_family      JetBrainsMono Nerd Font
bold_font        JetBrainsMono Nerd Font Bold
italic_font      JetBrainsMono Nerd Font Italic
font_size        12.5

# Colores Tokyo Night
foreground              #c0caf5
background              #1a1b26
selection_foreground    #1a1b26
selection_background    #33467c

color0  #15161e
color1  #f7768e
color2  #9ece6a
color3  #e0af68
color4  #7aa2f7
color5  #bb9af7
color6  #7dcfff
color7  #a9b1d6
color8  #414868
color9  #f7768e
color10 #9ece6a
color11 #e0af68
color12 #7aa2f7
color13 #bb9af7
color14 #7dcfff
color15 #c0caf5

# Cursor
cursor            #c0caf5
cursor_text_color #1a1b26
cursor_shape      beam
cursor_blink_interval 0.5

# Ventana
background_opacity 0.85
window_padding_width 10
hide_window_decorations yes
# Blur para que se vea bien el wallpaper detrás del terminal semi-transparente
background_blur 30

# Tab bar
tab_bar_style powerline
tab_powerline_style slanted
active_tab_foreground   #1a1b26
active_tab_background   #7aa2f7
inactive_tab_foreground #545c7e
inactive_tab_background #1a1b26

# Scroll
scrollback_lines 10000

# URLs
url_color #7aa2f7
url_style curly
